source "https://rubygems.org"
gem "jekyll", "~> 3.9.0"
gem "github-pages","~> 210" , group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
end
