source "https://rubygems.org"
gem "minima", git: "https://github.com/jekyll/minima"
gem "jekyll", "~> 3.9.0"
gem "github-pages","~> 210" , group: :jekyll_plugins
gem 'jekyll-sass-converter'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
end
